### ISSUE TITLE
Printing a print expression throws NullPointerException

### ISSUE THREAD

**Issue by MatthewKosloski** [MatthewKosloski/torrey#1]
Given the input via standard input:

```
(println (print 42))
```

The compiler outputs the following stack trace:

```
Exception in thread "main" java.lang.NullPointerException
        at me.mtk.torrey.backend.targets.x86_64.pc.linux.gen.Generator.gen(Generator.java:379)
        at me.mtk.torrey.backend.targets.x86_64.pc.linux.gen.Generator.gen(Generator.java:143)
        at me.mtk.torrey.backend.targets.x86_64.pc.linux.X8664PCLinuxBackend.generate(X8664PCLinuxBackend.java:26)
        at me.mtk.torrey.backend.targets.x86_64.pc.linux.X8664PCLinuxBackend.generate(X8664PCLinuxBackend.java:1)
        at me.mtk.torrey.Torrey.main(Torrey.java:82)
```

**Comment by MatthewKosloski** [comment]
Ideally, it should print "undefined" or "nil" to the standard output stream.  I haven't yet decided on the semantics.  Before, this should have thrown an error during type checking.

**Comment by MatthewKosloski** [comment]
Resolved in [PR 7](https://github.com/MatthewKosloski/torrey/pull/7).
