### ISSUE TITLE
Printing the difference between two numbers throws a NumberFormatException

### ISSUE THREAD

**Issue by MatthewKosloski** [MatthewKosloski/torrey#2]
Given the input via standard input:

```
(print (- 2 3))
```

The compiler outputs the following stack trace:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "-"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:642)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at me.mtk.torrey.frontend.ir.addressing.ConstAddress.<init>(ConstAddress.java:20)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:192)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:166)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:1)
        at me.mtk.torrey.frontend.ast.BinaryExpr.accept(BinaryExpr.java:32)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:251)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:1)
        at me.mtk.torrey.frontend.ast.PrintExpr.accept(PrintExpr.java:22)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:99)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.visit(IRGenVisitor.java:1)
        at me.mtk.torrey.frontend.ast.Program.accept(Program.java:21)
        at me.mtk.torrey.frontend.ir.gen.IRGenVisitor.gen(IRGenVisitor.java:82)
        at me.mtk.torrey.frontend.TorreyFrontend.irGen(TorreyFrontend.java:170)
        at me.mtk.torrey.frontend.TorreyFrontend.run(TorreyFrontend.java:38)
        at me.mtk.torrey.Torrey.main(Torrey.java:71)
```

**Comment by MatthewKosloski** [comment]
Resolved by [this](https://github.com/MatthewKosloski/torrey/commit/bffdb88859d506d73c5418dcbedbfeda1254e9d6) commit.  Thanks for the help, Ian!
