### ISSUE TITLE
Given an invalid target, the compiler throws a NullPointerException

### ISSUE THREAD

**Issue by MatthewKosloski** [MatthewKosloski/torrey#9]
When the CLI is given an invalid target triple supplied to the `-t` flag, the compiler should inform the user that the target is invalid/not registered.  However, currently, the compiler throws a `NullPointerException` which is unhelpful and bad UX

## Expected Behavior

Given an invalid/unregistered target, the compiler adequately informs the user via an error message to `stderr` and the JVM exists with a successful error code:

```
$ echo "(println 42)" | java -jar torreyc-3.0.2.jar -t some_invalid_target
"some_invalid_target" is not a registered target triple.  Use --target-list for more information.
```

## Actual Behavior

```
$ echo "(println 42)" | java -jar torreyc-3.0.2.jar -t some_invalid_target
Exception in thread "main" java.lang.NullPointerException
        at me.mtk.torrey.TorreyConfig.target(TorreyConfig.java:105)
        at me.mtk.torrey.Torrey.main(Torrey.java:40)
```

**Comment by MatthewKosloski** [comment]
The JVM should _NOT_ exit with a successful error code.

**Comment by MatthewKosloski** [comment]
Resolved by [this](https://github.com/MatthewKosloski/torrey/commit/7b42cf6694e7b361f95ac9eabc784523dbf6ff00) commit.
